import { useEffect, useRef, useState } from 'react'
import { Album, Camera, Heart, MapPin, MessageCircleHeart, Send, Volume2, VolumeX, Trash2, Upload, ImagePlus, LogOut, Download } from 'lucide-react'
import { supabase } from './lib/supabase'

const EVENT_DATE = new Date('2026-08-27T20:00:00+03:00')
const MAP_URL = 'https://maps.app.goo.gl/5ZTEqBQ7FyvxmEnp9?g_st=iw'
const YOUTUBE_URL = 'https://www.youtube-nocookie.com/embed/cNGjD0VG4R8?autoplay=1&loop=1&playlist=cNGjD0VG4R8&playsinline=1&rel=0'
const navItems=[['album','Album',Album],['camera','Camera',Camera],['location','Location',MapPin],['rsvp','RSVP',Heart],['wishes','Wishes',MessageCircleHeart]]
function timeLeft(){const d=Math.max(0,EVENT_DATE-Date.now()),t=Math.floor(d/1000);return{days:Math.floor(t/86400),hours:Math.floor(t%86400/3600),minutes:Math.floor(t%3600/60),seconds:t%60}}
function uid(){return crypto.randomUUID()}
async function ensureGuest(){if(!supabase)return null;const {data:{session}}=await supabase.auth.getSession();if(session)return session;const {data,error}=await supabase.auth.signInAnonymously();return error?null:data.session}
function App(){return location.pathname==='/admin'?<Admin/>:<Invitation/>}
function Invitation(){
 const [opened,setOpened]=useState(false),[music,setMusic]=useState(true),[clock,setClock]=useState(timeLeft()),[active,setActive]=useState('home')
 const [story,setStory]=useState([]),[wishes,setWishes]=useState([]),[memories,setMemories]=useState([]),[frame,setFrame]=useState(''),[session,setSession]=useState(null)
 const [wishName,setWishName]=useState(''),[wishText,setWishText]=useState(''),[rsvpName,setRsvpName]=useState(''),[attendance,setAttendance]=useState(true),[guests,setGuests]=useState(1)
 const [camera,setCamera]=useState(null),[photo,setPhoto]=useState(null),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),videoRef=useRef(null)
 useEffect(()=>{const x=setInterval(()=>setClock(timeLeft()),1000);return()=>clearInterval(x)},[])
 useEffect(()=>{(async()=>{const s=await ensureGuest();setSession(s);await load()})()},[])
 useEffect(()=>{const ids=['home','album','location','camera','rsvp','wishes'];const ob=new IntersectionObserver(es=>{const x=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(x)setActive(x.target.id)},{threshold:[.35,.65]});ids.forEach(id=>document.getElementById(id)&&ob.observe(document.getElementById(id)));return()=>ob.disconnect()},[opened])
 async function load(){if(!supabase)return;const [w,s,m,f]=await Promise.all([supabase.from('wishes').select('*').order('created_at',{ascending:false}),supabase.from('story_photos').select('*').order('sort_order').order('created_at'),supabase.from('memory_photos').select('*').order('created_at',{ascending:false}),supabase.from('site_settings').select('value').eq('key','frame_url').maybeSingle()]);if(w.data)setWishes(w.data);if(s.data)setStory(s.data);if(m.data)setMemories(m.data);if(f.data?.value)setFrame(f.data.value)}
 const go=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'})
 async function startCamera(){try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});setCamera(s);requestAnimationFrame(()=>{if(videoRef.current){videoRef.current.srcObject=s;videoRef.current.play()}});setNotice('Camera ready — smile ❤️')}catch{setNotice('Please allow camera access. Camera requires HTTPS.')}}
 function stop(){camera?.getTracks().forEach(t=>t.stop());setCamera(null)}
 function capture(){if(!videoRef.current)return;const v=videoRef.current,c=document.createElement('canvas'),size=1000;c.width=size;c.height=size;const k=Math.max(size/v.videoWidth,size/v.videoHeight);c.getContext('2d').drawImage(v,(size-v.videoWidth*k)/2,(size-v.videoHeight*k)/2,v.videoWidth*k,v.videoHeight*k);setPhoto(c.toDataURL('image/jpeg',.94));stop();setNotice('Photo captured. Add it to our Memory Wall.')}
 async function framedBlob(){if(!photo)return null;const out=document.createElement('canvas'),size=1200;out.width=out.height=size;const ctx=out.getContext('2d'),p=await image(photo),scale=Math.max(size/p.width,size/p.height);ctx.drawImage(p,(size-p.width*scale)/2,(size-p.height*scale)/2,p.width*scale,p.height*scale);if(frame){const f=await image(frame);ctx.drawImage(f,0,0,size,size)}return new Promise(r=>out.toBlob(r,'image/jpeg',.94))}
 async function saveMemory(){const blob=await framedBlob();if(!blob)return;setSaving(true);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Abanoub-Engy-Engagement.jpg';a.click();if(supabase&&session){const path=`${session.user.id}/${uid()}.jpg`;const up=await supabase.storage.from('memory-photos').upload(path,blob,{contentType:'image/jpeg'});if(up.error)setNotice('Downloaded, but upload failed.');else{const url=supabase.storage.from('memory-photos').getPublicUrl(path).data.publicUrl;const {data,error}=await supabase.from('memory_photos').insert({image_url:url,owner_id:session.user.id,storage_path:path}).select().single();if(!error)setMemories(x=>[data,...x])}}setSaving(false);setNotice('Downloaded to your phone and shared with everyone ❤️')}
 async function deleteMemory(m){if(!session||m.owner_id!==session.user.id)return;if(supabase){await supabase.from('memory_photos').delete().eq('id',m.id);if(m.storage_path)await supabase.storage.from('memory-photos').remove([m.storage_path]);setMemories(x=>x.filter(a=>a.id!==m.id))}}
 async function wish(e){e.preventDefault();if(!wishName||!wishText)return;const row={name:wishName.trim(),text:wishText.trim()};if(supabase){const {data,error}=await supabase.from('wishes').insert(row).select().single();if(error){setNotice('Could not send the wish.');return}setWishes(x=>[data,...x])}setWishName('');setWishText('');setNotice('Your wish is now visible to everyone ❤️')}
 async function rsvp(e){e.preventDefault();if(!rsvpName)return;if(supabase)await supabase.from('rsvps').insert({name:rsvpName.trim(),attendance,guests:Number(guests)});setRsvpName('');setNotice('Thank you for your RSVP ❤️')}
 return <main className="site-shell">
  {!opened&&<div className="opening"><div className="opening-glow"/><div className="opening-content"><p className="eyebrow">A little invitation to a beautiful beginning</p><h1>Abanoub <span>&</span> Engy</h1><p className="opening-subtitle">IT'S OUR ENGAGEMENT</p><p className="opening-date">THURSDAY · 27 AUGUST 2026</p><button className="primary-btn" onClick={()=>setOpened(true)}>Open Invitation <Heart size={16}/></button></div></div>}
  {opened&&music&&<iframe className="music-frame" src={YOUTUBE_URL} title="Our song" allow="autoplay; encrypted-media"/>}
  <nav className="top-nav"><button className="brand" onClick={()=>go('home')}>A & E</button><span>OUR ENGAGEMENT</span><button className="music-btn" onClick={()=>setMusic(!music)}>{music?<Volume2 size={17}/>:<VolumeX size={17}/>}</button></nav>
  <section id="home" className="hero section"><div className="hero-copy"><p className="eyebrow">Together with our families</p><h1>Abanoub <span>&</span><br/><em>Engy</em></h1><p className="hero-date">IT'S OUR ENGAGEMENT · 27 AUGUST 2026</p><div className="home-countdown">{Object.entries(clock).map(([k,v])=><div key={k}><strong>{String(v).padStart(2,'0')}</strong><span>{k}</span></div>)}</div><button className="scroll-cue" onClick={()=>go('album')}>Scroll to our story ↓</button></div></section>
  <section id="album" className="section paper album-section"><div className="section-inner"><p className="eyebrow">Album</p><h2>Our story,<br/><em>in moments.</em></h2><div className="story-grid">{story.length?story.map((p,i)=><img key={p.id} className={i===0?'story-img large':'story-img'} src={p.image_url} alt="Our story"/>):<div className="story-placeholder large"><span>Our story photos will appear here.</span></div>}</div><p className="gallery-note">Our Story is managed from the private Admin link.</p></div></section>
  <section id="location" className="section location-section"><div className="section-inner narrow"><p className="eyebrow">The day</p><h2>Meet us at<br/><em>St. George.</em></h2><div className="event-card"><span>THURSDAY · 27 AUGUST 2026</span><h3>8:00 PM</h3><p>ST. GEORGE CHURCH<br/>BANHA</p><div className="event-divider"/><p>CELEBRATION<br/><strong>ST. GEORGE CHURCH ROOFTOP</strong><br/>BANHA</p><a className="outline-btn" href={MAP_URL} target="_blank" rel="noreferrer"><MapPin size={16}/> Open Location</a></div></div></section>
  <section id="camera" className="section camera-section"><div className="section-inner"><p className="eyebrow">Create your memory</p><h2>Take a photo<br/><em>with our frame.</em></h2><div className="camera-stage">{camera?<video ref={videoRef} className="camera-video" playsInline muted/>:photo?<img className="captured-photo" src={photo} alt="Captured"/>:<div className="frame-empty">Your camera photo<br/>will appear here</div>}{frame&&<img className="real-frame" src={frame} alt="Abanoub and Engy frame"/>}</div><div className="camera-actions">{!camera&&!photo&&<button className="primary-btn" onClick={startCamera}><Camera size={16}/> Take Photo</button>}{camera&&<button className="primary-btn" onClick={capture}><Camera size={16}/> Capture</button>}{photo&&<><button className="outline-btn light" onClick={startCamera}>Retake</button><button className="download-btn" disabled={saving} onClick={saveMemory}>{saving?'Saving…':'Download + Share Photo'}</button></>}</div><p className="camera-note">Camera only. No Gallery picker. Your framed photo is visible to everyone after saving.</p><p className="notice">{notice}</p></div></section>
  <section className="section memories-section"><div className="section-inner"><p className="eyebrow">Memory wall</p><h2>Moments from<br/><em>our guests.</em></h2><div className="memory-grid">{memories.map(m=><article key={m.id}><img src={m.image_url} alt="Guest memory"/><div className="memory-actions"><a href={m.image_url} download target="_blank" rel="noreferrer"><Download size={14}/> Download</a>{session&&m.owner_id===session.user.id&&<button onClick={()=>deleteMemory(m)}><Trash2 size={14}/> Delete</button>}</div></article>)}</div>{!memories.length&&<p className="gallery-note">Be the first to create a memory.</p>}</div></section>
  <section id="rsvp" className="section paper rsvp-section"><div className="section-inner narrow"><p className="eyebrow">RSVP</p><h2>Will you<br/><em>join us?</em></h2><form className="invite-form" onSubmit={rsvp}><input value={rsvpName} onChange={e=>setRsvpName(e.target.value)} placeholder="Your name" required/><div className="choice-row"><button type="button" className={attendance?'choice active':'choice'} onClick={()=>setAttendance(true)}>Yes, I'll be there</button><button type="button" className={!attendance?'choice active':'choice'} onClick={()=>setAttendance(false)}>Sorry, I can't</button></div><select value={guests} onChange={e=>setGuests(e.target.value)}><option value="1">1 Guest</option><option value="2">2 Guests</option><option value="3">3 Guests</option><option value="4">4 Guests</option></select><button className="primary-btn dark" type="submit">Confirm RSVP <Send size={15}/></button></form></div></section>
  <section id="wishes" className="section wishes-section"><div className="section-inner narrow"><p className="eyebrow">A little love from you</p><h2>Leave us<br/><em>a wish.</em></h2><form className="invite-form" onSubmit={wish}><input value={wishName} onChange={e=>setWishName(e.target.value)} placeholder="Your name" required/><textarea value={wishText} onChange={e=>setWishText(e.target.value)} placeholder="Write your wish for Abanoub & Engy..." rows="4" required/><button className="primary-btn dark" type="submit">Send Your Wish <MessageCircleHeart size={15}/></button></form><div className="wishes-list">{wishes.map(w=><article key={w.id}><Heart size={14} fill="currentColor"/><p>“{w.text}”</p><span>— {w.name}</span></article>)}</div></div></section>
  <section className="section final"><div className="final-content"><p className="eyebrow">Why we invited you</p><h2>Be part of<br/><em>our beginning.</em></h2><p className="final-message">We don't want you to simply attend our engagement.<br/>We want you to be part of the beginning of our story.</p><div className="heart-line"><Heart size={16} fill="currentColor"/></div><h3>Abanoub & Engy</h3><p>27 · 08 · 2026</p></div></section>
  <div className="bottom-nav">{navItems.map(([id,label,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>go(id)}><Icon size={19}/><span>{label}</span></button>)}</div><footer>Made with love · Abanoub & Engy</footer>
 </main>
}
function image(src){return new Promise((ok,bad)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>ok(i);i.onerror=bad;i.src=src})}
function Admin(){
 const [session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[story,setStory]=useState([]),[wishes,setWishes]=useState([]),[rsvps,setRsvps]=useState([]),[memories,setMemories]=useState([]),[frame,setFrame]=useState(''),[status,setStatus]=useState('')
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[])
 useEffect(()=>{if(session)load()},[session])
 async function load(){const [s,w,r,m,f]=await Promise.all([supabase.from('story_photos').select('*').order('sort_order').order('created_at'),supabase.from('wishes').select('*').order('created_at',{ascending:false}),supabase.from('rsvps').select('*').order('created_at',{ascending:false}),supabase.from('memory_photos').select('*').order('created_at',{ascending:false}),supabase.from('site_settings').select('value').eq('key','frame_url').maybeSingle()]);setStory(s.data||[]);setWishes(w.data||[]);setRsvps(r.data||[]);setMemories(m.data||[]);setFrame(f.data?.value||'')}
 async function login(e){e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setStatus(error.message)}
 async function uploadStory(e){for(const file of [...e.target.files]){const path=`story/${uid()}-${file.name}`;const up=await supabase.storage.from('story-photos').upload(path,file,{upsert:false});if(!up.error){const url=supabase.storage.from('story-photos').getPublicUrl(path).data.publicUrl;await supabase.from('story_photos').insert({image_url:url,storage_path:path,sort_order:story.length});}}e.target.value='';load()}
 async function uploadFrame(e){const file=e.target.files?.[0];if(!file)return;const path=`frame/${uid()}-${file.name}`;const up=await supabase.storage.from('site-assets').upload(path,file,{upsert:true,contentType:file.type});if(up.error){setStatus(up.error.message);return}const url=supabase.storage.from('site-assets').getPublicUrl(path).data.publicUrl;await supabase.from('site_settings').upsert({key:'frame_url',value:url});setFrame(url);setStatus('Frame updated.');e.target.value=''}
 async function remove(table,row){if(!confirm('Delete this item?'))return;await supabase.from(table).delete().eq('id',row.id);load()}
 if(!supabase)return <div className="admin-page"><h1>Backend is not configured</h1><p>Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel.</p></div>
 if(!session)return <div className="admin-page"><div className="admin-card"><p className="eyebrow">Private access</p><h1>Abanoub & Engy<br/><em>Admin</em></h1><form className="invite-form" onSubmit={login}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" required/><button className="primary-btn dark">Login <LogOut size={15}/></button></form><p className="notice">{status}</p></div></div>
 return <div className="admin-page"><div className="admin-wrap"><div className="admin-head"><div><p className="eyebrow">Private dashboard</p><h1>Abanoub & Engy <em>Admin</em></h1></div><button className="outline-btn" onClick={()=>supabase.auth.signOut()}>Log out</button></div><div className="admin-grid"><div className="admin-card"><h2>Our Story</h2><label className="upload-box"><Upload/> Add photos from mobile Gallery<input hidden type="file" accept="image/*" multiple onChange={uploadStory}/></label><div className="admin-images">{story.map(x=><article key={x.id}><img src={x.image_url}/><button onClick={()=>remove('story_photos',x)}><Trash2 size={14}/></button></article>)}</div></div><div className="admin-card"><h2>Camera Frame</h2>{frame&&<img className="admin-frame-preview" src={frame}/>}<label className="upload-box"><ImagePlus/> Upload your exact frame image<input hidden type="file" accept="image/*" onChange={uploadFrame}/></label></div><div className="admin-card"><h2>RSVP <span>{rsvps.length}</span></h2><div className="table">{rsvps.map(x=><div key={x.id}><b>{x.name}</b><span>{x.attendance?'YES':'NO'} · {x.guests} guest(s)</span><button onClick={()=>remove('rsvps',x)}><Trash2 size={14}/></button></div>)}</div></div><div className="admin-card"><h2>Wishes <span>{wishes.length}</span></h2><div className="table">{wishes.map(x=><div key={x.id}><div><b>{x.name}</b><p>{x.text}</p></div><button onClick={()=>remove('wishes',x)}><Trash2 size={14}/></button></div>)}</div></div><div className="admin-card"><h2>Guest Memories <span>{memories.length}</span></h2><div className="admin-images">{memories.map(x=><article key={x.id}><img src={x.image_url}/><button onClick={()=>remove('memory_photos',x)}><Trash2 size={14}/></button></article>)}</div></div></div></div></div>
}
export default App
