import {useEffect,useState} from 'react'
import {Album,Camera,Heart,MapPin,MessageCircleHeart,Send,Volume2,VolumeX,Trash2,Upload,ImagePlus,LogOut,Download,RefreshCw,Users,Save} from 'lucide-react'
import {supabase} from './lib/supabase'
const EVENT_DATE=new Date('2026-08-27T20:00:00+03:00'),MAP_URL='https://maps.app.goo.gl/5ZTEqBQ7FyvxmEnp9?g_st=iw',YT='https://www.youtube-nocookie.com/embed/cNGjD0VG4R8?autoplay=1&loop=1&playlist=cNGjD0VG4R8&playsinline=1&rel=0'
const NAV=[['album','Story',Album],['camera','Camera',Camera],['location','Location',MapPin],['rsvp','RSVP',Heart],['wishes','Wishes',MessageCircleHeart]],emptyArea={x:25,y:25,w:50,h:50},uid=()=>crypto.randomUUID()
const countdown=()=>{const s=Math.max(0,Math.floor((EVENT_DATE-Date.now())/1000));return{days:Math.floor(s/86400),hours:Math.floor(s%86400/3600),minutes:Math.floor(s%3600/60),seconds:s%60}}
const loadImage=src=>new Promise((r,j)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>r(i);i.onerror=j;i.src=src})
async function guestSession(){if(!supabase)return null;const{data:{session}}=await supabase.auth.getSession();if(session)return session;const{data,error}=await supabase.auth.signInAnonymously();return error?null:data.session}
function App(){return location.pathname==='/admin'?<Admin/>:<Invitation/>}
function Invitation(){
 const[opened,setOpened]=useState(false),[music,setMusic]=useState(true),[clock,setClock]=useState(countdown()),[active,setActive]=useState('home'),[story,setStory]=useState([]),[memories,setMemories]=useState([]),[wishes,setWishes]=useState([]),[frame,setFrame]=useState(''),[area,setArea]=useState(emptyArea),[stream,setStream]=useState(null),[facing,setFacing]=useState('user'),[photo,setPhoto]=useState(null),[session,setSession]=useState(null),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[wName,setWName]=useState(''),[wText,setWText]=useState(''),[rName,setRName]=useState(''),[attending,setAttending]=useState(true),[guests,setGuests]=useState(1)
 useEffect(()=>{const t=setInterval(()=>setClock(countdown()),1000);return()=>clearInterval(t)},[])
 useEffect(()=>{guestSession().then(setSession)},[])
 useEffect(()=>{if(!supabase)return;load()},[])
 useEffect(()=>{if(!supabase)return;const channel=supabase.channel('memory-wall-live').on('postgres_changes',{event:'INSERT',schema:'public',table:'memory_photos'},payload=>setMemories(current=>current.some(m=>m.id===payload.new.id)?current:[payload.new,...current])).on('postgres_changes',{event:'DELETE',schema:'public',table:'memory_photos'},payload=>setMemories(current=>current.filter(m=>m.id!==payload.old.id))).subscribe();return()=>{supabase.removeChannel(channel)}},[])
 useEffect(()=>{if(!opened)return;const ids=['home','album','location','camera','rsvp','wishes'],obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{threshold:.35});ids.forEach(id=>{const el=document.getElementById(id);if(el)obs.observe(el)});return()=>obs.disconnect()},[opened])
 async function load(){if(!supabase)return;const[s,w,m,st]=await Promise.all([supabase.from('story_photos').select('*').order('sort_order').order('created_at'),supabase.from('wishes').select('*').order('created_at',{ascending:false}),supabase.from('memory_photos').select('*').order('created_at',{ascending:false}),supabase.from('site_settings').select('key,value').in('key',['frame_url','camera_area'])]);setStory(s.data||[]);setWishes(w.data||[]);setMemories(m.data||[]);setFrame(st.data?.find(x=>x.key==='frame_url')?.value||'');const a=st.data?.find(x=>x.key==='camera_area')?.value;if(a)try{setArea({...emptyArea,...JSON.parse(a)})}catch{}}
 function go(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setActive(id)}
 async function startCamera(next=facing){try{stream?.getTracks().forEach(t=>t.stop());const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:next},width:{ideal:1920},height:{ideal:1080}},audio:false});setFacing(next);setStream(s);setNotice(next==='user'?'Front camera ready ❤️':'Back camera ready ❤️');setTimeout(()=>{const el=document.querySelector('.camera-video');if(el){el.srcObject=s;el.setAttribute('playsinline','true');el.muted=true;el.onloadedmetadata=()=>el.play().catch(()=>{});el.play().catch(()=>{})}},150)}catch{setNotice('Please allow camera access. Camera works on HTTPS mobile browsers.')}}
 function stopCamera(){stream?.getTracks().forEach(t=>t.stop());setStream(null)}
 function capture(){const v=document.querySelector('.camera-video');if(!v||!v.videoWidth){setNotice('Camera is not ready yet. Please wait a moment.');return}const c=document.createElement('canvas');c.width=v.videoWidth||1280;c.height=v.videoHeight||720;const x=c.getContext('2d');if(facing==='user'){x.translate(c.width,0);x.scale(-1,1)}x.drawImage(v,0,0,c.width,c.height);setPhoto(c.toDataURL('image/jpeg',.95));stopCamera();setNotice('Photo ready. Preview it inside your frame.')}
 async function makeFinal(){if(!photo)return null;const f=frame?await loadImage(frame).catch(()=>null):null,p=await loadImage(photo),W=1400,H=f?Math.round(1400*(f.height/f.width)):1400,c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,W,H);if(f)x.drawImage(f,0,0,W,H);const px=W*area.x/100,py=H*area.y/100,pw=W*area.w/100,ph=H*area.h/100,scale=Math.max(pw/p.width,ph/p.height);x.save();x.beginPath();x.rect(px,py,pw,ph);x.clip();x.drawImage(p,px+(pw-p.width*scale)/2,py+(ph-p.height*scale)/2,p.width*scale,p.height*scale);x.restore();return new Promise(r=>c.toBlob(r,'image/jpeg',.95))}
 async function downloadBlob(blob){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='Abanoub-Engy-Engagement.jpg';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 async function saveMemory(){const blob=await makeFinal();if(!blob)return;setSaving(true);if(!supabase||!session){await downloadBlob(blob);setSaving(false);setNotice('Saved to your phone. Backend is not configured.');return}const path=`${session.user.id}/${uid()}.jpg`,up=await supabase.storage.from('memory-photos').upload(path,blob,{contentType:'image/jpeg'});if(up.error){setSaving(false);setNotice('Upload failed: '+up.error.message);return}const url=supabase.storage.from('memory-photos').getPublicUrl(path).data.publicUrl,{data,error}=await supabase.from('memory_photos').insert({image_url:url,owner_id:session.user.id,storage_path:path}).select().single();if(error){await supabase.storage.from('memory-photos').remove([path]);setSaving(false);setNotice('Database save failed: '+error.message);return}setMemories(m=>[data,...m]);await downloadBlob(blob);setPhoto(null);setSaving(false);setNotice('Saved, shared with everyone, and downloaded ❤️')}
 async function deleteMemory(m){if(!supabase||!session||m.owner_id!==session.user.id)return;const{error}=await supabase.from('memory_photos').delete().eq('id',m.id);if(!error){if(m.storage_path)await supabase.storage.from('memory-photos').remove([m.storage_path]);setMemories(x=>x.filter(y=>y.id!==m.id));setNotice('Your memory was deleted.')}}
 async function downloadMemory(m){try{const r=await fetch(m.image_url);await downloadBlob(await r.blob())}catch{window.open(m.image_url,'_blank')}}
 async function sendWish(e){e.preventDefault();if(!wName.trim()||!wText.trim())return;const{data,error}=await supabase.from('wishes').insert({name:wName.trim(),text:wText.trim()}).select().single();if(error){setNotice(error.message);return}setWishes(x=>[data,...x]);setWName('');setWText('');setNotice('Your wish is visible to everyone ❤️')}
 async function rsvp(e){e.preventDefault();const{error}=await supabase.from('rsvps').insert({name:rName.trim(),attendance:attending,guests:Number(guests)});if(error){setNotice(error.message);return}setRName('');setNotice('RSVP received ❤️')}
 return <main className="site-shell"><h1>Engagement</h1></main>
}
function Admin(){return <main className="site-shell"><h1>Admin</h1></main>}
export default App
