import { useEffect, useRef, useState } from 'react'
import { Album, Camera, Heart, MapPin, MessageCircleHeart, Send, Volume2, VolumeX, Trash2, Upload, ImagePlus, LogOut, Download, RefreshCw, Check, Users } from 'lucide-react'
import { supabase } from './lib/supabase'

const EVENT_DATE = new Date('2026-08-27T20:00:00+03:00')
const MAP_URL = 'https://maps.app.goo.gl/5ZTEqBQ7FyvxmEnp9?g_st=iw'
const YOUTUBE_URL = 'https://www.youtube-nocookie.com/embed/cNGjD0VG4R8?autoplay=1&loop=1&playlist=cNGjD0VG4R8&playsinline=1&rel=0'
const navItems=[['album','Story',Album],['camera','Camera',Camera],['location','Location',MapPin],['rsvp','RSVP',Heart],['wishes','Wishes',MessageCircleHeart]]

function timeLeft(){const d=Math.max(0,EVENT_DATE-Date.now()),t=Math.floor(d/1000);return{days:Math.floor(t/86400),hours:Math.floor(t%86400/3600),minutes:Math.floor(t%3600/60),seconds:t%60}}
function uid(){return crypto.randomUUID()}
function image(src){return new Promise((ok,bad)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>ok(i);i.onerror=bad;i.src=src})}
async function ensureGuest(){if(!supabase)return null;const {data:{session}}=await supabase.auth.getSession();if(session)return session;const {data,error}=await supabase.auth.signInAnonymously();return error?null:data.session}

function App(){return location.pathname==='/admin'?<Admin/>:<Invitation/>}

function Invitation(){
 const [opened,setOpened]=useState(false),[closing,setClosing]=useState(false),[music,setMusic]=useState(true),[clock,setClock]=useState(timeLeft()),[active,setActive]=useState('home')
 const [story,setStory]=useState([]),[wishes,setWishes]=useState([]),[memories,setMemories]=useState([]),[frame,setFrame]=useState(''),[session,setSession]=useState(null)
 const [wishName,setWishName]=useState(''),[wishText,setWishText]=useState(''),[rsvpName,setRsvpName]=useState(''),[attendance,setAttendance]=useState(true),[guests,setGuests]=useState(1)
 const [camera,setCamera]=useState(null),[facing,setFacing]=useState('user'),[photo,setPhoto]=useState(null),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),videoRef=useRef(null)
 useEffect(()=>{const x=setInterval(()=>setClock(timeLeft()),1000);return()=>clearInterval(x)},[])
 useEffect(()=>{(async()=>{const s=await ensureGuest();setSession(s);load()})()},[])
 useEffect(()=>{if(!opened)return;const ids=['home','album','location','camera','rsvp','wishes'];const ob=new IntersectionObserver(es=>{const x=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(x)setActive(x.target.id)},{threshold:[.35,.65]});ids.forEach(id=>document.getElementById(id)&&ob.observe(document.getElementById(id)));return()=>ob.disconnect()},[opened])
 async function load(){if(!supabase)return;const [w,s,m,f]=await Promise.all([supabase.from('wishes').select('*').order('created_at',{ascending:false}),supabase.from('story_photos').select('*').order('sort_order').order('created_at'),supabase.from('memory_photos').select('*').order('created_at',{ascending:false}),supabase.from('site_settings').select('value').eq('key','frame_url').maybeSingle()]);if(w.data)setWishes(w.data);if(s.data)setStory(s.data);if(m.data)setMemories(m.data);if(f.data?.value)setFrame(f.data.value)}
 const go=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'})
 function openInvitation(){setClosing(true);setTimeout(()=>setOpened(true),650)}
 async function startCamera(nextFacing=facing){try{camera?.getTracks().forEach(t=>t.stop());const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:nextFacing},width:{ideal:1280},height:{ideal:1280}},audio:false});setFacing(nextFacing);setCamera(s);requestAnimationFrame(()=>{if(videoRef.current){videoRef.current.srcObject=s;videoRef.current.play()}});setNotice(nextFacing==='user'?'Front camera ready — smile ❤️':'Back camera ready — capture the moment ❤️')}catch{setNotice('Please allow camera access. Camera requires HTTPS.')}}
 function stop(){camera?.getTracks().forEach(t=>t.stop());setCamera(null)}
 function capture(){if(!videoRef.current)return;const v=videoRef.current,c=document.createElement('canvas'),size=1200;c.width=size;c.height=size;const ctx=c.getContext('2d');const k=Math.max(size/v.videoWidth,size/v.videoHeight);ctx.drawImage(v,(size-v.videoWidth*k)/2,(size-v.videoHeight*k)/2,v.videoWidth*k,v.videoHeight*k);setPhoto(c.toDataURL('image/jpeg',.95));stop();setNotice('Photo captured. Now save your framed memory.')}
 async function framedBlob(){if(!photo)return null;const out=document.createElement('canvas'),size=1400;out.width=out.height=size;const ctx=out.getContext('2d'),p=await image(photo),scale=Math.max(size/p.width,size/p.height);ctx.drawImage(p,(size-p.width*scale)/2,(size-p.height*scale)/2,p.width*scale,p.height*scale);if(frame){try{const f=await image(frame);ctx.drawImage(f,0,0,size,size)}catch{setNotice('Frame preview failed to load.')}}return new Promise(r=>out.toBlob(r,'image/jpeg',.95))}
 async function downloadBlob(blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Abanoub-Engy-Engagement.jpg';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function saveMemory(){const blob=await framedBlob();if(!blob)return;setSaving(true);if(supabase&&session){const path=`${session.user.id}/${uid()}.jpg`;const up=await supabase.storage.from('memory-photos').upload(path,blob,{contentType:'image/jpeg'});if(up.error){await downloadBlob(blob);setNotice('Saved to your phone, but sharing failed.');setSaving(false);return}const url=supabase.storage.from('memory-photos').getPublicUrl(path).data.publicUrl;const {data,error}=await supabase.from('memory_photos').insert({image_url:url,owner_id:session.user.id,storage_path:path}).select().single();if(error){await supabase.storage.from('memory-photos').remove([path]);await downloadBlob(blob);setNotice('Saved to your phone, but sharing failed.');setSaving(false);return}setMemories(x=>[data,...x]);await downloadBlob(blob);setPhoto(null);setSaving(false);setNotice('Your framed memory is live for everyone ❤️')}else{await downloadBlob(blob);setSaving(false);setNotice('Saved to your phone. Backend is not configured.')}}
 async function deleteMemory(m){if(!session||m.owner_id!==session.user.id||!supabase)return;const {error}=await supabase.from('memory_photos').delete().eq('id',m.id);if(!error){if(m.storage_path)await supabase.storage.from('memory-photos').remove([m.storage_path]);setMemories(x=>x.filter(a=>a.id!==m.id));setNotice('Your memory was removed.')}}
 async function downloadMemory(m){try{const res=await fetch(m.image_url);const blob=await res.blob();await downloadBlob(blob)}catch{window.open(m.image_url,'_blank')}}
 async function wish(e){e.preventDefault();if(!wishName.trim()||!wishText.trim())return;if(supabase){const {data,error}=await supabase.from('wishes').insert({name:wishName.trim(),text:wishText.trim()}).select().single();if(error){setNotice('Could not send the wish.');return}setWishes(x=>[data,...x])}setWishName('');setWishText('');setNotice('Your wish is now visible to everyone ❤️')}
 async function rsvp(e){e.preventDefault();if(!rsvpName.trim())return;if(supabase){const {error}=await supabase.from('rsvps').insert({name:rsvpName.trim(),attendance,guests:Number(guests)});if(error){setNotice('Could not save RSVP.');return}}setRsvpName('');setNotice('Thank you for your RSVP ❤️')}
 return <main className="site-shell">
  {!opened&&<div className={`opening ${closing?'opening-closing':''}`}><div className="curtain curtain-top"/><div className="curtain curtain-bottom"/><div className="opening-content"><p className="eyebrow">A little invitation to a beautiful beginning</p><h1><span className="name-word">Abanoub</span> <i>&</i> <span className="name-word">Engy</span></h1><p className="opening-subtitle">IT'S OUR ENGAGEMENT</p><p className="opening-date">THURSDAY · 27 AUGUST 2026</p><button className="primary-btn" onClick={openInvitation}>Open Invitation <Heart size={16}/></button></div></div>}
  {opened&&music&&<iframe className="music-frame" src={YOUTUBE_URL} title="Our song" allow="autoplay; encrypted-media"/>}
  <nav className="top-nav"><button className="brand" onClick={()=>go('home')}>A & E</button><span>OUR ENGAGEMENT</span><button className="music-btn" onClick={()=>setMusic(!music)}>{music?<Volume2 size={17}/>:<VolumeX size={17}/>}</button></nav>
  <section id="home" className="hero section"><div className="hero-copy"><p className="eyebrow hero-reveal">Together with our families</p><h1><span>Abanoub</span><i>&</i><em>Engy</em></h1><p className="hero-date hero-reveal">IT'S OUR ENGAGEMENT · 27 AUGUST 2026</p><div className="countdown-wrap"><p>OUR DAY IS GETTING CLOSER</p><div className="home-countdown">{Object.entries(clock).map(([k,v],i)=><div key={k} className={`count-cell c${i}`}><strong>{String(v).padStart(2,'0')}</strong><span>{k}</span></div>)}</div></div><button className="scroll-cue" onClick={()=>go('album')}>Follow our journey <span>↓</span></button></div></section>
  <section id="album" className="section paper album-section"><div className="section-inner"><p className="eyebrow">Our story</p><h2>A little journey,<br/><em>one moment at a time.</em></h2><div className="story-path">{story.length?story.map((p,i)=><article className={`story-step ${i%2?'right':'left'}`} key={p.id}><div className="story-dot"/><div className="story-card"><div className="story-image-wrap"><img src={p.image_url} alt="Our story"/></div><div className="story-copy"><span>{new Date(p.created_at).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase()}</span><p>{i===0?'The beginning of another beautiful chapter.':i===1?'A memory we will always keep close.':'Another little moment from our journey.'}</p></div></div></article>):<div className="story-placeholder"><span>Our story photos will appear here.</span></div>}</div><p className="gallery-note">Photos and moments are managed from your private Admin link.</p></div></section>
  <section id="location" className="section location-section"><div className="section-inner narrow"><p className="eyebrow">The day</p><h2>Meet us at<br/><em>St. George.</em></h2><div className="event-card"><span>THURSDAY · 27 AUGUST 2026</span><h3>8:00 PM</h3><p>PRAYER<br/><strong>ST. GEORGE CHURCH · BANHA</strong></p><div className="event-divider"/><p>OUR CELEBRATION<br/><strong>ST. GEORGE CHURCH ROOFTOP · BANHA</strong></p><a className="outline-btn" href={MAP_URL} target="_blank" rel="noreferrer"><MapPin size={16}/> Open Location</a></div></div></section>
  <section id="camera" className="section camera-section"><div className="section-inner"><p className="eyebrow">Create your memory</p><h2>Become part of<br/><em>our celebration.</em></h2>{frame&&<div className="frame-showcase"><img src={frame} alt="Our engagement frame"/><span>OUR OFFICIAL FRAME</span></div>}<div className="camera-stage">{camera?<video ref={videoRef} className="camera-video" playsInline muted/>:photo?<img className="captured-photo" src={photo} alt="Captured"/>:<div className="frame-empty"><Camera size={35}/><span>Your camera photo<br/>appears inside the frame</span></div>}{frame&&<img className="real-frame" src={frame} alt="Abanoub and Engy frame"/>}</div><div className="camera-actions">{!camera&&!photo&&<button className="primary-btn" onClick={()=>startCamera('user')}><Camera size={16}/> Take Photo</button>}{camera&&<><button className="primary-btn" onClick={capture}><Camera size={16}/> Capture</button><button className="outline-btn light" onClick={()=>startCamera(facing==='user'?'environment':'user')}><RefreshCw size={16}/> {facing==='user'?'Back Camera':'Front Camera'}</button></>}{photo&&<><button className="outline-btn light" onClick={()=>startCamera(facing)}><RefreshCw size={16}/> Retake</button><button className="download-btn" disabled={saving} onClick={saveMemory}>{saving?'Saving…':'Save + Share Memory'}</button></>}</div><p className="camera-note">Camera only — no Gallery picker. Flip between front and back camera. Your framed photo becomes visible to everyone after saving.</p><p className="notice">{notice}</p></div></section>
  <section className="section memories-section"><div className="section-inner"><p className="eyebrow">Memory wall</p><h2>Moments from<br/><em>our guests.</em></h2><div className="memory-grid">{memories.map(m=><article key={m.id}><img src={m.image_url} alt="Guest memory"/><div className="memory-actions"><button onClick={()=>downloadMemory(m)}><Download size={14}/> Save</button>{session&&m.owner_id===session.user.id&&<button onClick={()=>deleteMemory(m)}><Trash2 size={14}/> Delete</button>}</div></article>)}</div>{!memories.length&&<p className="gallery-note">Be the first to create a memory.</p>}</div></section>
  <section id="rsvp" className="section paper rsvp-section"><div className="section-inner narrow"><p className="eyebrow">RSVP</p><h2>Will you<br/><em>join us?</em></h2><form className="invite-form" onSubmit={rsvp}><input value={rsvpName} onChange={e=>setRsvpName(e.target.value)} placeholder="Your name" required/><div className="choice-row"><button type="button" className={attendance?'choice active':'choice'} onClick={()=>setAttendance(true)}>Yes, I'll be there</button><button type="button" className={!attendance?'choice active':'choice'} onClick={()=>setAttendance(false)}>Sorry, I can't</button></div><label className="number-field"><Users size={15}/><span>Number of guests</span><input type="number" min="1" max="10" step="1" inputMode="numeric" value={guests} onChange={e=>setGuests(Math.max(1,Math.min(10,Number(e.target.value)||1)))} /></label><button className="primary-btn dark" type="submit">Confirm RSVP <Send size={15}/></button></form></div></section>
  <section id="wishes" className="section wishes-section"><div className="section-inner narrow"><p className="eyebrow">A little love from you</p><h2>Leave us<br/><em>a wish.</em></h2><form className="invite-form" onSubmit={wish}><input value={wishName} onChange={e=>setWishName(e.target.value)} placeholder="Your name" required/><textarea value={wishText} onChange={e=>setWishText(e.target.value)} placeholder="Write your wish for Abanoub & Engy..." rows="4" required/><button className="primary-btn dark" type="submit">Send Your Wish <MessageCircleHeart size={15}/></button></form><div className="wishes-list">{wishes.map(w=><article key={w.id}><Heart size={14} fill="currentColor"/><p>“{w.text}”</p><span>— {w.name}</span></article>)}</div></div></section>
  <section className="section final"><div className="final-content"><p className="eyebrow">Why we invited you</p><h2>Be part of<br/><em>our beginning.</em></h2><p className="final-message">We don't want you to simply attend our engagement.<br/>We want you to be part of the beginning of our story.</p><div className="heart-line"><Heart size={16} fill="currentColor"/></div><h3>Abanoub & Engy</h3><p>27 · 08 · 2026</p></div></section>
  <div className="bottom-nav">{navItems.map(([id,label,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>go(id)}><Icon size={19}/><span>{label}</span></button>)}</div><footer>Made with love · Abanoub & Engy</footer>
 </main>
}

function Admin(){
 const [session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[story,setStory]=useState([]),[wishes,setWishes]=useState([]),[rsvps,setRsvps]=useState([]),[memories,setMemories]=useState([]),[frame,setFrame]=useState(''),[status,setStatus]=useState(''),[storyBusy,setStoryBusy]=useState(false),[frameBusy,setFrameBusy]=useState(false)
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[])
 useEffect(()=>{if(session)load()},[session])
 async function load(){const [s,w,r,m,f]=await Promise.all([supabase.from('story_photos').select('*').order('sort_order').order('created_at'),supabase.from('wishes').select('*').order('created_at',{ascending:false}),supabase.from('rsvps').select('*').order('created_at',{ascending:false}),supabase.from('memory_photos').select('*').order('created_at',{ascending:false}),supabase.from('site_settings').select('value').eq('key','frame_url').maybeSingle()]);setStory(s.data||[]);setWishes(w.data||[]);setRsvps(r.data||[]);setMemories(m.data||[]);setFrame(f.data?.value||'')}
 async function login(e){e.preventDefault();const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setStatus(error.message)}
 async function uploadStory(e){setStoryBusy(true);for(const file of [...e.target.files]){const path=`story/${uid()}-${file.name}`;const up=await supabase.storage.from('story-photos').upload(path,file,{upsert:false});if(!up.error){const url=supabase.storage.from('story-photos').getPublicUrl(path).data.publicUrl;await supabase.from('story_photos').insert({image_url:url,storage_path:path,sort_order:story.length});}}e.target.value='';await load();setStoryBusy(false);setStatus('Story updated.')}
 async function uploadFrame(e){const file=e.target.files?.[0];if(!file)return;setFrameBusy(true);const path=`frame/${uid()}-${file.name}`;const up=await supabase.storage.from('site-assets').upload(path,file,{upsert:false,contentType:file.type});if(up.error){setStatus(up.error.message);setFrameBusy(false);return}const url=supabase.storage.from('site-assets').getPublicUrl(path).data.publicUrl;await supabase.from('site_settings').upsert({key:'frame_url',value:url});setFrame(url);setFrameBusy(false);setStatus('Frame updated.') ;e.target.value=''}
 async function remove(table,row){if(!confirm('Delete this item?'))return;const {error}=await supabase.from(table).delete().eq('id',row.id);if(!error&&row.storage_path){const bucket=table==='story_photos'?'story-photos':table==='memory_photos'?'memory-photos':'site-assets';await supabase.storage.from(bucket).remove([row.storage_path])}await load()}
 if(!supabase)return <div className="admin-page"><div className="admin-card admin-login"><h1>Backend is not configured</h1><p>Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel.</p></div></div>
 if(!session)return <div className="admin-page"><div className="admin-card admin-login"><p className="eyebrow">Private access</p><h1>Abanoub & Engy<br/><em>Admin</em></h1><form className="invite-form" onSubmit={login}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" required/><button className="primary-btn dark">Login <LogOut size={15}/></button></form><p className="notice">{status}</p></div></div>
 const yes=rsvps.filter(x=>x.attendance).length,no=rsvps.filter(x=>!x.attendance).length,total=rsvps.reduce((n,x)=>n+(x.attendance?Number(x.guests):0),0)
 return <div className="admin-page"><div className="admin-wrap"><div className="admin-head"><div><p className="eyebrow">Private dashboard</p><h1>Abanoub & Engy <em>Admin</em></h1></div><button className="outline-btn" onClick={()=>supabase.auth.signOut()}>Log out</button></div><div className="stats-row"><div><strong>{rsvps.length}</strong><span>RSVP</span></div><div><strong>{yes}</strong><span>YES</span></div><div><strong>{total}</strong><span>GUESTS</span></div><div><strong>{memories.length}</strong><span>MEMORIES</span></div></div><div className="admin-grid"><div className="admin-card"><h2>Our Story <span>{story.length}</span></h2><label className="upload-box"><Upload/><span>{storyBusy?'Uploading…':'Add photos from mobile Gallery'}</span><input hidden type="file" accept="image/*" multiple onChange={uploadStory}/></label><div className="admin-images">{story.map(x=><article key={x.id}><img src={x.image_url}/><button onClick={()=>remove('story_photos',x)}><Trash2 size={14}/></button></article>)}</div></div><div className="admin-card"><h2>Camera Frame</h2>{frame&&<div className="admin-frame-wrap"><img className="admin-frame-preview" src={frame}/><p>This exact frame is shown on the public Camera section.</p></div>}<label className="upload-box"><ImagePlus/><span>{frameBusy?'Uploading…':'Upload / replace frame from Gallery'}</span><input hidden type="file" accept="image/*" onChange={uploadFrame}/></label></div><div className="admin-card"><h2>RSVP <span>{rsvps.length}</span></h2><div className="table">{rsvps.map(x=><div key={x.id}><div><b>{x.name}</b><span>{x.attendance?'YES':'NO'} · {x.guests} guest(s)</span></div><button onClick={()=>remove('rsvps',x)}><Trash2 size={14}/></button></div>)}</div></div><div className="admin-card"><h2>Wishes <span>{wishes.length}</span></h2><div className="table">{wishes.map(x=><div key={x.id}><div><b>{x.name}</b><p>{x.text}</p></div><button onClick={()=>remove('wishes',x)}><Trash2 size={14}/></button></div>)}</div></div><div className="admin-card admin-wide"><h2>Guest Memories <span>{memories.length}</span></h2><div className="admin-memory-grid">{memories.map(x=><article key={x.id}><img src={x.image_url}/><div><button onClick={()=>window.open(x.image_url,'_blank')}><Download size={14}/> Save</button><button onClick={()=>remove('memory_photos',x)}><Trash2 size={14}/> Delete</button></div></article>)}</div>{!memories.length&&<p className="gallery-note">Guest photos will appear here after they save a framed memory.</p>}</div></div><p className="admin-status">{status}</p></div></div>
}
export default App
